version: '3.8' # Specifies the version of the Docker Compose file format

services:
  app:
    build:
      context: . # The context specifies the root directory of your application
      dockerfile: Dockerfile # Use the Dockerfile in the root directory
    container_name: jcakes-app-img # Optional: Name the container
    image: jcakes-app-img
    ports:
      - "8081:8081" # Map the container's port 8081 to the host's port 8081
    volumes:
      - ./src:/jcakes/src # Bind mount the source code directory for live updates
      - /jcakes/node_modules # Exclude `node_modules` from being overwritten
    stdin_open: true # Keep the container open for interactive input
    tty: true # Allocate a pseudo-TTY for the container

# Optional: Define networks if needed for connecting multiple services
networks:
  default:
    driver: bridge
